### ISSUE TITLE
Please Release Version: 5.9.2

### ISSUE THREAD

**Issue by mpellicer** [webjars/dropzone#14]
Thanks

**Comment by jamesward** [comment]
Version `5.7.2` is the newest I can find for this.

**Comment by mpellicer** [comment]
I see the version in the repo:

https://github.com/enyo/dropzone/

![image](https://user-images.githubusercontent.com/8653754/127435487-911d8f02-454a-407c-875a-fc658e898b35.png)

Maybe you're releasing from a different repo, in that case no problem, I'm fine closing this.

Thank you so much for your help, I'm trying to switch some of the libraries to NPM so we don't need to use the classic method and disturb anybody!

**Comment by mpellicer** [comment]
Okay, look like they moved the repository!

![image](https://user-images.githubusercontent.com/8653754/127436126-ef3f095e-98db-4895-912a-614a05ffc4c6.png)

Webjars is using this:
https://gitlab.com/meno/dropzone
And the new one is this:
https://github.com/enyo/dropzone/

Not sure if we can switch but I'm fine using 5.7.2, thanks James

**Comment by jamesward** [comment]
Thanks for figuring that out! This will be released shortly.
