### ISSUE TITLE
Please Release Version: 5.3

### ISSUE THREAD

**Issue by KarlKl** [webjars/dropzone#9]
There is a complete new version 5 available. The webjar is at version 4.x.
https://gitlab.com/meno/dropzone

**Comment by jamesward** [comment]
Can you point me to the `5.3` release?  I'm only seeing `5.2.0` in what appears as their new home: https://gitlab.com/meno/dropzone/tags

**Comment by KarlKl** [comment]
Oh sorry. You are right, the current version is 5.2.
I tought there is a 5.3 because in the [release notes](https://gitlab.com/meno/dropzone/blob/master/CHANGELOG.md) there is one announced.
